spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: liquibase/changelog-master.yml

